# .github/workflows/github-pages.yml

name: Build and deploy this site to GitHub Pages

on:
    push:
        branches:
            - jekyll

jobs:
    github-pages:
        runs-on: ubuntu-latest
        steps:
            - name: ğŸ“‚ checkout repo
              uses: actions/checkout@v4.1.1
            - name: ğŸ’ setup ruby
              uses: ruby/setup-ruby@v1
              with:
                  ruby-version: 3.1
                  bundler-cache: true
            - name: ğŸ“¦ node setup
              uses: actions/setup-node@v4
              with:
                  node-version: "18"
            - run: npm install
            - name: ğŸ”¨ install dependencies & build site
              uses: limjh16/jekyll-action-ts@v2.4.1
              with:
                  enable_cache: true
                  format_output: true
                  jekyll_env: production
            - name: ğŸš€ deploy site
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./_site
